Wolox/express-js-bootstrap

package.json, test/app.js, test/authMiddleware.js, test/users.js
`Prettier` resolved a bug of new line per chained method. In some weird cases it did not detect them, but now it does.
I'm aware this is not the way the majority of us like to see the chained method. In the future, the first message will be next to the object and the rest of them in new lines as we agreed, but this will be in another PR.
=> Fixing prettier bug

app/models/scripts/dataCreation.js
- Fixing local tests returning bcrypt promise
=> Returning bcrypt promise

migrations/index.js
- Executing migrations when they are pending to run
=> Running migrations

package.json
* Updated jwt-simple package to latest version, nsp found a security issue with the version we had before.
=> Upgraded jwt version according to nsp issue

.eslintrc, package.json
- Resolving eslint prettier dependencies
- Deleting duplicated dependencies
- Removing `request` package not used
- Resolving #47
=> Fixing dependencies

.travis.yml, README.md, scripts/readme-initializer.js
- Changing readme title
- FIxing script
=> FIxing readme

.travis.yml, scripts/errors-initializer.js, scripts/models-initializer.js, scripts/routes-initializer.js
https://trello.com/c/62XTpAtj/61-fixes-prettier-y-posibles-cambios-de-reglas
=> adapting init to prettier

package.json, pull_request_template.md
* Added pull request template.
* Added Wolox as author in package.json
=> Added pull request template and some changes in package.json

config/index.js, package-lock.json, package.json
* Moved the dotenv require to the config index file, because it was not working for db migrations.
=> Changed dotenv implementation

migrations/migrations/20170526115728-user-create.js, migrations/migrations/20170526115919-books-create.js
=> fixing migrations

app/errors.js, app/middlewares/errors.js, docs/books.html, docs/users.html, test/books.js, test/users.js
Refactored error's middleware. Now, everywhere in the app, when an error is thrown no status code is attached. Then, error's middleware will take the internal code the thrown error has and get is corresponding status code.
=> Refactored errors middleware responsibilities

.woloxci/Dockerfile, .woloxci/config.yml, Jenkinsfile, config/index.js
=> Enables woloxci

app/logger/index.js, migrations/index.js
- Changing harcoded directories
https://trello.com/c/sHmAianO/67-arreglar-logger-de-nacho
=> Fixing directory problems

README.md, scripts/models-initializer.js
- Modify some litle lines to avoid error during kickoff script;
- Modify README on database point;
There is style an issue when running kick-off script. It seems because `scripts/` is deleted before running the script.
=> Correction on model script and README

README.md, app/middlewares/errors.js, scripts/errors-initializer.js, scripts/kick-off.js, scripts/models-initializer.js, scripts/packagejson-initializer.js, scripts/readme-initializer.js, scripts/routes-initializer.js, scripts/scripts-initializer.js
* Kickoff script fixes:
- Changed model initializer to keep new refactor, reported on issue #73.
- Changed errors initializer to keep new errors refactor.
- Fixed some error logs that didn't logged the correct var.
- Fixed errors middleware unused var, reported on issue #76.
- Moved dataCreation script to /scripts folder, according to orm refactor.
* Some readme changes
* The errors middleware is being generated in the kickoff with some unused status codes.
* The dataCreation script should be deleted, but I left it until we implement FactoryGirl here.
=> Kickoff script Fixed

Dockerfile, Dockerrun.aws.json
Adds Dockerfile and Dockerrun.aws.json to deploy in AWS Elastic Beanstalk
=> Adds Dockerfile and Dockerrun.aws.json for AWS EB deploy

app/logger/index.js, package-lock.json, package.json
- Rollbacking logger version and code
=> rollbacking logger version

app.js, package-lock.json, package.json
- CORS is a node.js package for providing a Connect/Express middleware
that can be used to enable CORS
- The use of cors should a little more configure;
=> Add cors package

app.js, config/index.js
=> adding port env var

app/controllers/healthCheck.js, app/routes.js, docs/books.html, docs/users.html, scripts/controllers-initializer.js, scripts/routes-initializer.js, scripts/tests-initializer.js, test/healthCheck.js
- Adding healthcheck endpoint with uptime
=> Health check

generators/app/constants.js, generators/app/index.js, generators/app/utils.js, package-lock.json, package.json
- Fixes #101 
- Make optional git url for kickoff
=> Fix some git problems

generators/app/templates/Procfile, package-lock.json, package.json, test/__snapshots__/deploy.spec.js.snap
- FIxed procfile to use `node server.js` instead of `node app.js`
=> Fixed procfile to deploy on heroku

generators/app/templates/package.json, package-lock.json, package.json
I am implementing what we discussed about the scripts in the training. https://3.basecamp.com/4113302/buckets/10320888/messages/1816217089
The `migrations-test` script is removed in order to make trainees create it.
Also I am fixing vulnerabilities.
=> Test card in training refactor

generators/app/constants.js, generators/app/prompts.js, generators/app/templates/.travis.yml, generators/app/templates/.woloxci/config.yml, generators/app/templates/README.md, generators/app/templates/config/db.ejs, generators/app/templates/config/development.ejs, generators/app/templates/config/production.ejs, generators/app/templates/config/testing.ejs, generators/app/templates/console.ejs, generators/app/templates/package.json, generators/app/templates/server.ejs, generators/app/templates/test/app.spec.ejs, generators/app/utils.js, package-lock.json, test/__snapshots__/mongoose.spec.js.snap, test/helpers/constants.js, test/mongoose.spec.js, test/sequelize.spec.js
- Added new ORM mongoose and dialect mongoDB.
=> Added new orm mongoose

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_proposal.md, generators/app/templates/.github/ISSUE_TEMPLATE/bug_report.md, generators/app/templates/.github/ISSUE_TEMPLATE/feature_proposal.md
**Implement issue templates in both generator and project template**.
None
=> Implement issue templates in both generator and project template

generators/app/templates/config/db.ejs, test/__snapshots__/mongoose.spec.js.snap
- Modified db.js for mongoose because of new linter.
=> modified file for new linter

generators/app/constants.js, generators/app/templates/app.ejs, generators/app/templates/package.json, test/__snapshots__/general.spec.js.snap, test/__snapshots__/optionals.spec.js.snap
Summary
---
Implement [Helmet.js middleware](https://helmetjs.github.io/) in express app. It is optional, and should be selected in the prompt.
For more information about Helmet, read [Security best practices from Express documentation](https://expressjs.com/en/advanced/best-practice-security.html?source=post_page---------------------------#use-helmet).
=> Implement helmet middleware for secure express app

generators/app/constants.js, generators/app/templates/README.md, generators/app/templates/app.ejs, generators/app/templates/documentation.js, generators/app/templates/documentation/index.js, generators/app/templates/documentation/paths/index.js, generators/app/templates/documentation/paths/user.js, generators/app/templates/documentation/schemas.js, generators/app/templates/documentation/schemas/index.js, generators/app/templates/documentation/schemas/user.js, generators/app/templates/package.json, package-lock.json, test/__snapshots__/general.spec.js.snap, test/__snapshots__/mongoose.spec.js.snap, test/__snapshots__/optionals.spec.js.snap, test/__snapshots__/sequelize.spec.js.snap, test/__snapshots__/testing.spec.js.snap, test/helpers/constants.js
I added Open Api documentation.
RIP dictum :heart:
=> Open api documentation

generators/app/templates/app.ejs, generators/app/templates/package.json, test/__snapshots__/general.spec.js.snap, test/__snapshots__/mongoose.spec.js.snap, test/__snapshots__/optionals.spec.js.snap, test/__snapshots__/sequelize.spec.js.snap, test/__snapshots__/testing.spec.js.snap
- Update logger version to 1.1.0
=> Update version of logger

generators/app/templates/config/db.ejs, test/__snapshots__/general.spec.js.snap, test/__snapshots__/sequelize.spec.js.snap
adding port field to `config/db.js` file.
No known issues.
[trello card](https://trello.com/c/pYtH3kbW/115-agregar-campo-port-al-archivo-config-dbjs)
=> adding port field to dbConfig file

generators/app/templates/test/factory/factory_by_models.ejs
- Refactored factory-by-models and fixed linter
=> refactored factory by models

CHANGELOG.md, generators/app/templates/package.json, test/__snapshots__/general.spec.js.snap, test/__snapshots__/mongoose.spec.js.snap, test/__snapshots__/optionals.spec.js.snap, test/__snapshots__/sequelize.spec.js.snap, test/__snapshots__/testing.spec.js.snap
add scripts de seeds
https://trello.com/c/F7U1cmt0
=> add the scrips to create the seeds in the template

CHANGELOG.md, generators/app/templates/package.json, test/__snapshots__/general.spec.js.snap, test/__snapshots__/mongoose.spec.js.snap, test/__snapshots__/optionals.spec.js.snap, test/__snapshots__/sequelize.spec.js.snap, test/__snapshots__/testing.spec.js.snap
It was calling "npm run start", not "npm run start --coverage".
No known issues.
No trello card.
=> Cover script fixed.

.github/release-drafter.yml, .github/workflows/npm-publish.yml, .github/workflows/release-drafter.yml, CHANGELOG.md, README.md
- Add github actions
- Update year of changelog
- Deprecate old changelog
=> Add github actions

.github/workflows/auto-approve.yml
- Add github action for auto approve PRs from dependabot
=> Add github action for auto-approve

.github/workflows/auto-approve.yml
- Change auto-approve.yml to auto-merge dependabot.
=> Change auto-approve config

generators/app/index.js, generators/app/utils.js, package.json
=> Delete unused mkdrip package

generators/app/templates/config/index.ejs, test/__snapshots__/general.spec.js.snap
- Fix config function isObject because is detecting arrays as objects
=> Fix config isObject function

generators/app/templates/app/models/index.js
- Modifying `app/models/index.js` template, for `sequelize` model imports
=> fix: fixing sequelize model imports, due to sequelize version upgrade
